name: turning_point
dependencies:
    - python=3.10
    - black=22.6.0
    - flake8=4.0.1
    - isort=5.9.3
    - numpy=1.23.5
    - pandas=1.4.4
    - matplotlib=3.5.2
    - pytest=7.1.2
    - scipy=1.9.1
    - seaborn=0.11.2
    - jupyter
